### ISSUE TITLE
Documentation / Explanation of code

### ISSUE THREAD

**Issue by SaadBazaz** [mina-asham/XBox360ControllerManager#1]
Hello @mina-asham ,
I came across your code and would like to understand it to build a proper Xbox 360 Controller Manager. However, I'm having a tough time understanding the code.

Can you list out in your README about:
- What's working, and how
- How to compile and run your project
- Where you need to make improvements
- Any future plans

This stuff would help me and other users.

**Comment by mina-asham** [comment]
Hi @SaadBazaz,

Thanks for reaching out, I highly doubt that I will have enough time to write a comprehensive README here, but I can give you a few pointers that could help:
* Entry point is: https://github.com/mina-asham/XBox360ControllerManager/blob/master/XBox360ControllerManager/MainWindow.xaml.cs
* There is a timer that check if any of the xbox 360 controller buttons are pressed, the guide button will open up the application, B will hide is again, X will turn of the controller

The project is a vanilla XAML UI project, should open and build fine with Visual Studio.

Worth noting that the repo is 4 years old and I haven't been maintaining it, so I don't even know if this still works or not, specially in Windows 10 where the guide button loads the built-in xbox page.

Happy to accept any improvements/fixes through PR though :)

**Comment by SaadBazaz** [comment]
I really appreciate the guidance.

It's the precise issue which I want to fix - The guide button opens using an Xbox One controller, but not an Xbox 360 controller which I've connected through the Wireless Receiver. I thought I'd bring some life into the 360 controller, as they're flooding the second-hand market. Everyone deserves a chance to enjoy the cool Game Bar :D

### What I want to do
- Launch the Xbox Game Bar by pressing the GUIDE button
- Control the Xbox Game Bar using an Xbox 360 Controller
- Custom Widget for Xbox Game Bar (https://docs.microsoft.com/en-us/gaming/game-bar/)
- Power off single controller by holding the GUIDE button, or by launching the Xbox Game Bar and selecting the Custom Widget
- Power off multiple controllers by launching the Xbox Game Bar and selecting the Custom Widget

I'll be learning C# just for this mini-project, as it's required for the Game Bar Widget as well. Do need your prayers and good vibes. Might pester you with some small questions, totally up to you to answer.

I'll fork this repo and build it onwards. Thanks again!

**Comment by SaadBazaz** [comment]
It worked!

## How I loaded
- Download and install Visual Studio 2019 Community Edition with Universal Windows Development Package box selected.
- Download and install .NET Framework 4.6.1 from [here](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net461-developer-pack-offline-installer)
- Double click on .sln file in Windows Explorer
- Run

I'll start my journey from here on.
Thank you again.
